"use client"

import { useState } from "react"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { 
  Copy, 
  Check, 
  Loader2, 
  RefreshCw,
  Share2,
  MessageCircle,
  Twitter,
  Link2,
  Music,
  Camera,
  Play,
  Sparkles,
  TrendingUp,
  Clock,
  Eye,
  Heart,
  ChevronDown,
  ChevronUp,
  Volume2,
  Type,
  Hash,
  Wand2,
  Zap
} from "lucide-react"
import { clsx } from "clsx"

interface CaptionStyle {
  style: string
  text: string
  engagement: string
  emojis: string[]
  color: string
}

interface ScriptOutputProps {
  isLoading?: boolean
  data?: {
    hooks: string[]
    script: string
    caption: string
    hashtags: string
    hashtagsNiche: string[]
    hashtagsTrending: string[]
    audioSuggestions: {
      name: string
      artist: string
      trending: boolean
      plays: string
    }[]
    thumbnailIdeas: string[]
    bRollSuggestions: string[]
    sceneBreakdown: {
      time: string
      scene: string
      camera: string
    }[]
    captions: CaptionStyle[]
  }
  onRegenerate?: () => void
}

export function ScriptOutput({ isLoading, data, onRegenerate }: ScriptOutputProps) {
  const [copiedSection, setCopiedSection] = useState<string | null>(null)
  const [showShareMenu, setShowShareMenu] = useState(false)
  const [activeCaption, setActiveCaption] = useState(0)
  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>({
    hooks: true,
    script: true,
    captions: true,
    hashtags: false,
    audio: false,
    broll: false,
    thumbnail: false
  })

  const toggleSection = (section: string) => {
    setExpandedSections(prev => ({
      ...prev,
      [section]: !prev[section]
    }))
  }

  const copyToClipboard = async (text: string, section: string) => {
    try {
      await navigator.clipboard.writeText(text)
      setCopiedSection(section)
      setTimeout(() => setCopiedSection(null), 2000)
    } catch (err) {
      console.error("Failed to copy:", err)
    }
  }

  const shareToWhatsApp = () => {
    const text = encodeURIComponent(`Check out my new reel script!\n\n🎣 Hook: ${data?.hooks[0]}\n\n📝 Script: ${data?.script?.substring(0, 100)}...\n\nGenerated by ReelScript 🔥`)
    window.open(`https://wa.me/?text=${text}`, '_blank')
  }

  const shareToTwitter = () => {
    const text = encodeURIComponent(`Check out my new reel script! 🎬\n\nGenerated by @reelscript`)
    window.open(`https://twitter.com/intent/tweet?text=${text}`, '_blank')
  }

  const copyLink = () => {
    copyToClipboard(window.location.origin, "link")
    setShowShareMenu(false)
  }

  const shareCaptionToWhatsApp = () => {
    const caption = data?.captions?.[activeCaption]?.text || data?.caption || ""
    const text = encodeURIComponent(`${caption}\n\nGenerated by ReelScript 🔥`)
    window.open(`https://wa.me/?text=${text}`, '_blank')
  }

  const shareCaptionToTwitter = () => {
    const caption = data?.captions?.[activeCaption]?.text || data?.caption || ""
    const text = encodeURIComponent(`${caption.substring(0, 200)}...\n\nGenerated by @reelscript`)
    window.open(`https://twitter.com/intent/tweet?text=${text}`, '_blank')
  }

  const shareFullScript = () => {
    const fullText = `
🎣 HOOK:
${data?.hooks.join('\n')}

📝 SCRIPT:
${data?.script}

📝 CAPTION:
${data?.captions?.[activeCaption]?.text || data?.caption}

#️⃣ HASHTAGS:
${data?.hashtags}

🎵 AUDIO SUGGESTIONS:
${data?.audioSuggestions?.map(a => `${a.name} - ${a.artist}`).join('\n')}

Generated by ReelScript 🔥
    `.trim()
    copyToClipboard(fullText, "full")
    setShowShareMenu(false)
  }

  if (isLoading) {
    return (
      <div className="space-y-4">
        <Card className="p-8 bg-card border-border overflow-hidden relative">
          {/* Animated Background */}
          <div className="absolute inset-0 bg-gradient-to-br from-purple-500/5 via-pink-500/5 to-transparent" />
          <div className="absolute inset-0">
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-32 h-32 bg-purple-500/20 rounded-full blur-3xl animate-pulse" />
          </div>
          
          <div className="relative flex flex-col items-center justify-center py-16 space-y-6">
            <div className="relative">
              <div className="w-20 h-20 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center animate-pulse">
                <Sparkles className="h-10 w-10 text-white" />
              </div>
              <div className="absolute inset-0 w-20 h-20 rounded-full border-4 border-purple-500/30 animate-ping" />
            </div>
            
            <div className="text-center space-y-3">
              <div className="flex items-center justify-center gap-2">
                <span className="text-2xl">✨</span>
                <p className="text-xl font-semibold bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent">
                  Creating your viral script
                </p>
                <span className="text-2xl">✨</span>
              </div>
              <p className="text-sm text-muted-foreground max-w-md">
                Our AI is crafting the perfect hook, script, captions, and hashtags for you...
              </p>
            </div>
            
            {/* Progress Steps */}
            <div className="w-full max-w-md space-y-3">
              {[
                { text: "Generating viral hooks", done: true },
                { text: "Writing engaging script", done: true },
                { text: "Creating trending captions", done: false },
                { text: "Finding best hashtags", done: false },
              ].map((step, i) => (
                <div key={i} className="flex items-center gap-3 text-sm">
                  <div className={clsx(
                    "w-6 h-6 rounded-full flex items-center justify-center text-xs",
                    step.done ? "bg-green-500 text-white" : "bg-muted text-muted-foreground animate-pulse"
                  )}>
                    {step.done ? "✓" : i + 1}
                  </div>
                  <span className={clsx(
                    step.done ? "text-green-400" : "text-muted-foreground"
                  )}>
                    {step.text}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </Card>
      </div>
    )
  }

  if (!data) {
    return (
      <Card className="p-12 bg-card border-border border-dashed">
        <div className="flex flex-col items-center justify-center py-12 space-y-6 text-center">
          <div className="relative">
            <div className="h-24 w-24 rounded-full bg-gradient-to-br from-purple-500/20 to-pink-500/20 flex items-center justify-center group hover:scale-110 transition-transform cursor-pointer">
              <span className="text-5xl group-hover:animate-bounce transition-transform">🎬</span>
            </div>
            <div className="absolute -inset-4 bg-gradient-to-r from-purple-500/20 to-pink-500/20 rounded-full blur-xl -z-10" />
          </div>
          
          <div className="space-y-2">
            <p className="text-xl font-medium text-muted-foreground">
              Ready to create something viral?
            </p>
            <p className="text-sm text-muted-foreground max-w-sm">
              Enter your topic above and click "Generate Viral Script" to get started
            </p>
          </div>
          
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <Sparkles className="h-4 w-4 text-purple-400" />
            <span>Scripts generated in under 10 seconds</span>
            <Sparkles className="h-4 w-4 text-pink-400" />
          </div>
        </div>
      </Card>
    )
  }

  return (
    <div className="space-y-4">
      {/* Share Bar */}
      <Card className="overflow-hidden bg-gradient-to-r from-purple-500/10 via-pink-500/10 to-purple-500/10 border-purple-500/20">
        <div className="px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center">
              <Share2 className="h-5 w-5 text-white" />
            </div>
            <div>
              <p className="font-semibold">Share your script</p>
              <p className="text-xs text-muted-foreground">Spread the magic ✨</p>
            </div>
          </div>
          
          <div className="relative">
            <Button 
              className="bg-gradient-to-r from-purple-500 to-pink-500 hover:opacity-90 gap-2"
              onClick={() => setShowShareMenu(!showShareMenu)}
            >
              <Share2 className="h-4 w-4" />
              Share
            </Button>
            
            {showShareMenu && (
              <div className="absolute right-0 top-full mt-2 w-56 rounded-xl bg-card border border-border shadow-xl z-20 overflow-hidden animate-in fade-in slide-in-from-top-2">
                <button 
                  onClick={shareToWhatsApp}
                  className="w-full px-4 py-3 text-left text-sm hover:bg-green-500/10 flex items-center gap-3 transition-colors"
                >
                  <div className="h-8 w-8 rounded-lg bg-green-500 flex items-center justify-center">
                    <MessageCircle className="h-4 w-4 text-white" />
                  </div>
                  Share on WhatsApp
                </button>
                <button 
                  onClick={shareToTwitter}
                  className="w-full px-4 py-3 text-left text-sm hover:bg-blue-500/10 flex items-center gap-3 transition-colors"
                >
                  <div className="h-8 w-8 rounded-lg bg-blue-500 flex items-center justify-center">
                    <Twitter className="h-4 w-4 text-white" />
                  </div>
                  Share on Twitter/X
                </button>
                <button 
                  onClick={copyLink}
                  className="w-full px-4 py-3 text-left text-sm hover:bg-muted flex items-center gap-3 transition-colors"
                >
                  <div className="h-8 w-8 rounded-lg bg-muted flex items-center justify-center">
                    <Link2 className="h-4 w-4" />
                  </div>
                  Copy Link
                </button>
                <div className="border-t border-border" />
                <button 
                  onClick={shareFullScript}
                  className="w-full px-4 py-3 text-left text-sm hover:bg-purple-500/10 flex items-center gap-3 transition-colors font-medium"
                >
                  <div className="h-8 w-8 rounded-lg bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center">
                    <Copy className="h-4 w-4 text-white" />
                  </div>
                  Copy Full Script
                </button>
              </div>
            )}
          </div>
        </div>
      </Card>

      {/* Hooks Section */}
      <div className="space-y-2">
        <button 
          onClick={() => toggleSection('hooks')}
          className="w-full flex items-center justify-between p-4 rounded-xl bg-gradient-to-r from-amber-500/10 to-orange-500/10 border border-amber-500/20 hover:border-amber-500/40 transition-all group"
        >
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-amber-500 to-orange-500 flex items-center justify-center group-hover:scale-110 transition-transform">
              <span className="text-xl">🎣</span>
            </div>
            <div className="text-left">
              <p className="font-semibold">Hook (3 Options)</p>
              <p className="text-xs text-muted-foreground">Stop the scroll in 3 seconds</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Badge className="bg-amber-500/20 text-amber-400 border-0">🔥 Viral</Badge>
            {expandedSections.hooks ? <ChevronUp className="h-5 w-5" /> : <ChevronDown className="h-5 w-5" />}
          </div>
        </button>
        
        {expandedSections.hooks && (
          <div className="space-y-3 pl-4 border-l-2 border-amber-500/20 ml-5">
            {data.hooks.map((hook, index) => (
              <Card 
                key={index}
                className="p-4 bg-card border-amber-500/20 hover:border-amber-500/40 transition-all group cursor-pointer"
                onClick={() => copyToClipboard(hook, `hook-${index}`)}
              >
                <div className="flex items-start gap-4">
                  <div className="h-8 w-8 rounded-full bg-gradient-to-br from-amber-500 to-orange-500 flex items-center justify-center text-white text-sm font-bold flex-shrink-0">
                    {index + 1}
                  </div>
                  <p className="flex-1 text-sm leading-relaxed group-hover:text-amber-400 transition-colors">{hook}</p>
                  <Button
                    variant="ghost"
                    size="sm"
                    className="opacity-0 group-hover:opacity-100 transition-all h-8 w-8 p-0"
                  >
                    {copiedSection === `hook-${index}` ? (
                      <Check className="h-4 w-4 text-green-500" />
                    ) : (
                      <Copy className="h-4 w-4" />
                    )}
                  </Button>
                </div>
              </Card>
            ))}
          </div>
        )}
      </div>

      {/* AI Caption Generator */}
      {data.captions && data.captions.length > 0 && (
        <div className="space-y-2">
          <button 
            onClick={() => toggleSection('captions')}
            className="w-full flex items-center justify-between p-4 rounded-xl bg-gradient-to-r from-purple-500/10 to-pink-500/10 border border-purple-500/20 hover:border-purple-500/40 transition-all group"
          >
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center group-hover:scale-110 transition-transform">
                <Wand2 className="h-5 w-5 text-white" />
              </div>
              <div className="text-left">
                <p className="font-semibold">✨ AI Caption Generator</p>
                <p className="text-xs text-muted-foreground">5 trending styles</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Badge className="bg-purple-500/20 text-purple-400 border-0">🔥 Hot</Badge>
              {expandedSections.captions ? <ChevronUp className="h-5 w-5" /> : <ChevronDown className="h-5 w-5" />}
            </div>
          </button>
          
          {expandedSections.captions && (
            <Card className="p-6 bg-card border-purple-500/20">
              {/* Caption Style Tabs */}
              <div className="flex flex-wrap gap-2 mb-6">
                {data.captions.map((caption, index) => (
                  <button
                    key={index}
                    onClick={() => setActiveCaption(index)}
                    className={clsx(
                      "px-4 py-2 rounded-xl text-sm font-medium transition-all",
                      activeCaption === index
                        ? "text-white shadow-lg"
                        : "bg-muted hover:bg-muted/80 text-muted-foreground"
                    )}
                    style={{
                      background: activeCaption === index 
                        ? `linear-gradient(135deg, ${caption.color})` 
                        : undefined
                    }}
                  >
                    {caption.style}
                  </button>
                ))}
              </div>
              
              {/* Active Caption */}
              {data.captions[activeCaption] && (
                <div className="space-y-4">
                  <div 
                    className="p-6 rounded-xl bg-gradient-to-br from-muted/50 to-muted/20 border border-border relative overflow-hidden cursor-pointer hover:border-purple-500/40 transition-all group"
                    onClick={() => copyToClipboard(data.captions[activeCaption].text, `caption-${activeCaption}`)}
                  >
                    {/* Decorative Elements */}
                    <div className="absolute top-2 right-2 opacity-20">
                      <Sparkles className="h-8 w-8 text-purple-400" />
                    </div>
                    
                    <p className="text-sm leading-relaxed whitespace-pre-wrap relative z-10 group-hover:text-purple-400 transition-colors">
                      {data.captions[activeCaption].text}
                    </p>
                  </div>
                  
                  {/* Actions */}
                  <div className="flex items-center justify-between">
                    <div className="flex gap-2">
                      <Button
                        variant="outline"
                        size="sm"
                        className="gap-2"
                        onClick={() => copyToClipboard(data.captions[activeCaption].text, `caption-${activeCaption}`)}
                      >
                        {copiedSection === `caption-${activeCaption}` ? (
                          <Check className="h-4 w-4 text-green-500" />
                        ) : (
                          <Copy className="h-4 w-4" />
                        )}
                        Copy
                      </Button>
                    </div>
                    
                    <div className="flex gap-1">
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={shareCaptionToWhatsApp}
                        className="text-green-500 hover:text-green-400 hover:bg-green-500/10"
                      >
                        <MessageCircle className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={shareCaptionToTwitter}
                        className="text-blue-400 hover:text-blue-300 hover:bg-blue-500/10"
                      >
                        <Twitter className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                  
                  {/* Stats */}
                  <div className="flex items-center gap-4 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <Type className="h-3 w-3" />
                      {data.captions[activeCaption].text.length} chars
                    </span>
                    <span className="flex items-center gap-1">
                      <Clock className="h-3 w-3" />
                      {Math.ceil(data.captions[activeCaption].text.length / 5)}s read
                    </span>
                    <span className="flex items-center gap-1">
                      <TrendingUp className="h-3 w-3 text-green-400" />
                      {data.captions[activeCaption].engagement}
                    </span>
                  </div>
                </div>
              )}
            </Card>
          )}
        </div>
      )}

      {/* Hashtags Section */}
      <div className="space-y-2">
        <button 
          onClick={() => toggleSection('hashtags')}
          className="w-full flex items-center justify-between p-4 rounded-xl bg-gradient-to-r from-blue-500/10 to-cyan-500/10 border border-blue-500/20 hover:border-blue-500/40 transition-all group"
        >
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-blue-500 to-cyan-500 flex items-center justify-center group-hover:scale-110 transition-transform">
              <Hash className="h-5 w-5 text-white" />
            </div>
            <div className="text-left">
              <p className="font-semibold">#️⃣ Hashtags</p>
              <p className="text-xs text-muted-foreground">30+ trending tags</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Badge className="bg-blue-500/20 text-blue-400 border-0">📈 SEO</Badge>
            {expandedSections.hashtags ? <ChevronUp className="h-5 w-5" /> : <ChevronDown className="h-5 w-5" />}
          </div>
        </button>
        
        {expandedSections.hashtags && (
          <Card className="p-6 bg-card border-blue-500/20 space-y-4">
            {/* Niche Tags */}
            {data.hashtagsNiche && data.hashtagsNiche.length > 0 && (
              <div>
                <p className="text-xs text-muted-foreground mb-2 flex items-center gap-1">
                  <span className="text-purple-400">●</span> Niche Tags (Your Topic)
                </p>
                <div className="flex flex-wrap gap-2">
                  {data.hashtagsNiche.map((tag, index) => (
                    <Badge 
                      key={index} 
                      variant="secondary" 
                      className="px-3 py-1.5 text-sm hover:bg-purple-500/20 cursor-pointer transition-colors"
                    >
                      #{tag}
                    </Badge>
                  ))}
                </div>
              </div>
            )}
            
            {/* Trending Tags */}
            {data.hashtagsTrending && data.hashtagsTrending.length > 0 && (
              <div>
                <p className="text-xs text-muted-foreground mb-2 flex items-center gap-1">
                  <span className="text-amber-400">●</span> 🔥 Trending Tags
                </p>
                <div className="flex flex-wrap gap-2">
                  {data.hashtagsTrending.map((tag, index) => (
                    <Badge 
                      key={index} 
                      className="px-3 py-1.5 text-sm bg-gradient-to-r from-amber-500/20 to-orange-500/20 text-amber-400 border-0 hover:from-amber-500/30 hover:to-orange-500/30 cursor-pointer transition-colors"
                    >
                      #{tag}
                    </Badge>
                  ))}
                </div>
              </div>
            )}
            
            {/* Copy All */}
            <div className="pt-2 border-t border-border">
              <Button
                variant="outline"
                className="w-full gap-2"
                onClick={() => copyToClipboard(data.hashtags, "hashtags")}
              >
                {copiedSection === "hashtags" ? (
                  <Check className="h-4 w-4 text-green-500" />
                ) : (
                  <Copy className="h-4 w-4" />
                )}
                Copy All Hashtags
              </Button>
            </div>
          </Card>
        )}
      </div>

      {/* Trending Audio Section */}
      {data.audioSuggestions && data.audioSuggestions.length > 0 && (
        <div className="space-y-2">
          <button 
            onClick={() => toggleSection('audio')}
            className="w-full flex items-center justify-between p-4 rounded-xl bg-gradient-to-r from-green-500/10 to-emerald-500/10 border border-green-500/20 hover:border-green-500/40 transition-all group"
          >
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-green-500 to-emerald-500 flex items-center justify-center group-hover:scale-110 transition-transform">
                <Volume2 className="h-5 w-5 text-white" />
              </div>
              <div className="text-left">
                <p className="font-semibold">🎵 Trending Audio</p>
                <p className="text-xs text-muted-foreground">Hot sounds in India</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Badge className="bg-green-500/20 text-green-400 border-0">🔥 Trending</Badge>
              {expandedSections.audio ? <ChevronUp className="h-5 w-5" /> : <ChevronDown className="h-5 w-5" />}
            </div>
          </button>
          
          {expandedSections.audio && (
            <Card className="p-4 bg-card border-green-500/20 space-y-3">
              {data.audioSuggestions.map((audio, index) => (
                <div 
                  key={index}
                  className="flex items-center justify-between p-3 rounded-xl bg-muted/50 hover:bg-muted transition-colors group cursor-pointer"
                >
                  <div className="flex items-center gap-4">
                    <div className="h-12 w-12 rounded-xl bg-gradient-to-br from-green-500/20 to-emerald-500/20 flex items-center justify-center group-hover:scale-110 transition-transform relative">
                      <Play className="h-5 w-5 text-green-400 ml-1" fill="currentColor" />
                      {audio.trending && (
                        <div className="absolute -top-1 -right-1 w-4 h-4 rounded-full bg-red-500 animate-pulse" />
                      )}
                    </div>
                    <div>
                      <p className="text-sm font-medium group-hover:text-green-400 transition-colors">{audio.name}</p>
                      <p className="text-xs text-muted-foreground">{audio.artist}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    {audio.plays && (
                      <span className="text-xs text-muted-foreground hidden sm:block">{audio.plays}</span>
                    )}
                    {audio.trending && (
                      <Badge className="bg-red-500/20 text-red-400 border-0 text-xs">🔥 Hot</Badge>
                    )}
                  </div>
                </div>
              ))}
              <p className="text-xs text-muted-foreground text-center pt-2">
                💡 Search these in Instagram Reels to find trending sounds
              </p>
            </Card>
          )}
        </div>
      )}

      {/* B-Roll Section */}
      {data.bRollSuggestions && data.bRollSuggestions.length > 0 && (
        <div className="space-y-2">
          <button 
            onClick={() => toggleSection('broll')}
            className="w-full flex items-center justify-between p-4 rounded-xl bg-gradient-to-r from-orange-500/10 to-red-500/10 border border-orange-500/20 hover:border-orange-500/40 transition-all group"
          >
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-orange-500 to-red-500 flex items-center justify-center group-hover:scale-110 transition-transform">
                <Camera className="h-5 w-5 text-white" />
              </div>
              <div className="text-left">
                <p className="font-semibold">🎥 B-Roll Suggestions</p>
                <p className="text-xs text-muted-foreground">Visual ideas for your video</p>
              </div>
            </div>
            {expandedSections.broll ? <ChevronUp className="h-5 w-5" /> : <ChevronDown className="h-5 w-5" />}
          </button>
          
          {expandedSections.broll && (
            <Card className="p-4 bg-card border-orange-500/20">
              <div className="flex flex-wrap gap-2">
                {data.bRollSuggestions.map((item, index) => (
                  <Badge 
                    key={index} 
                    variant="secondary" 
                    className="px-4 py-2 text-sm hover:bg-orange-500/20 cursor-pointer transition-colors"
                    onClick={() => copyToClipboard(item, `broll-${index}`)}
                  >
                    {item}
                  </Badge>
                ))}
              </div>
            </Card>
          )}
        </div>
      )}

      {/* Scene Breakdown */}
      {data.sceneBreakdown && data.sceneBreakdown.length > 0 && (
        <div className="space-y-2">
          <button 
            onClick={() => toggleSection('script')}
            className="w-full flex items-center justify-between p-4 rounded-xl bg-gradient-to-r from-pink-500/10 to-rose-500/10 border border-pink-500/20 hover:border-pink-500/40 transition-all group"
          >
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-pink-500 to-rose-500 flex items-center justify-center group-hover:scale-110 transition-transform">
                <Zap className="h-5 w-5 text-white" />
              </div>
              <div className="text-left">
                <p className="font-semibold">📖 Full Script</p>
                <p className="text-xs text-muted-foreground">Scene-by-scene breakdown</p>
              </div>
            </div>
            {expandedSections.script ? <ChevronUp className="h-5 w-5" /> : <ChevronDown className="h-5 w-5" />}
          </button>
          
          {expandedSections.script && (
            <Card className="p-6 bg-card border-pink-500/20 space-y-4">
              {/* Timeline */}
              <div className="relative pl-6 border-l-2 border-pink-500/30 space-y-4">
                {data.sceneBreakdown.map((scene, index) => (
                  <div key={index} className="relative">
                    <div className="absolute -left-6 top-0 w-4 h-4 rounded-full bg-gradient-to-br from-pink-500 to-rose-500 border-2 border-card" />
                    <div className="flex items-start gap-4">
                      <span className="flex-shrink-0 px-2 py-1 rounded bg-pink-500/20 text-pink-400 text-xs font-medium">
                        {scene.time}
                      </span>
                      <div className="flex-1">
                        <p className="text-sm font-medium">{scene.scene}</p>
                        <p className="text-xs text-muted-foreground mt-1">📷 {scene.camera}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
              
              {/* Full Script Text */}
              <div 
                className="p-4 rounded-xl bg-muted/50 cursor-pointer hover:bg-muted transition-colors"
                onClick={() => copyToClipboard(data.script, "script")}
              >
                <pre className="text-sm whitespace-pre-wrap text-muted-foreground">
                  {data.script}
                </pre>
              </div>
              
              <Button
                variant="outline"
                className="w-full gap-2"
                onClick={() => copyToClipboard(data.script, "script")}
              >
                {copiedSection === "script" ? (
                  <Check className="h-4 w-4 text-green-500" />
                ) : (
                  <Copy className="h-4 w-4" />
                )}
                Copy Full Script
              </Button>
            </Card>
          )}
        </div>
      )}

      {/* Thumbnail Ideas */}
      {data.thumbnailIdeas && data.thumbnailIdeas.length > 0 && (
        <div className="space-y-2">
          <button 
            onClick={() => toggleSection('thumbnail')}
            className="w-full flex items-center justify-between p-4 rounded-xl bg-gradient-to-r from-violet-500/10 to-purple-500/10 border border-violet-500/20 hover:border-violet-500/40 transition-all group"
          >
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-violet-500 to-purple-500 flex items-center justify-center group-hover:scale-110 transition-transform">
                <Eye className="h-5 w-5 text-white" />
              </div>
              <div className="text-left">
                <p className="font-semibold">🖼️ Thumbnail Ideas</p>
                <p className="text-xs text-muted-foreground">For YouTube & Reels</p>
              </div>
            </div>
            {expandedSections.thumbnail ? <ChevronUp className="h-5 w-5" /> : <ChevronDown className="h-5 w-5" />}
          </button>
          
          {expandedSections.thumbnail && (
            <Card className="p-4 bg-card border-violet-500/20 space-y-3">
              {data.thumbnailIdeas.map((idea, index) => (
                <div 
                  key={index}
                  className="flex items-start gap-4 p-3 rounded-xl bg-muted/50 hover:bg-muted transition-colors cursor-pointer"
                  onClick={() => copyToClipboard(idea, `thumbnail-${index}`)}
                >
                  <Camera className="h-5 w-5 text-violet-400 mt-0.5 flex-shrink-0" />
                  <p className="text-sm">{idea}</p>
                </div>
              ))}
              <p className="text-xs text-muted-foreground text-center pt-2">
                💡 Use Canva or PicsArt to create these thumbnails
              </p>
            </Card>
          )}
        </div>
      )}

      {/* Regenerate Button */}
      <div className="pt-4">
        <Button
          variant="outline"
          onClick={onRegenerate}
          className="w-full h-12 text-base gap-2 bg-gradient-to-r from-purple-500/10 to-pink-500/10 border-purple-500/20 hover:border-purple-500/40 hover:bg-gradient-to-r hover:from-purple-500/20 hover:to-pink-500/20"
        >
          <RefreshCw className="h-5 w-5" />
          Generate Another Script
        </Button>
      </div>
    </div>
  )
}
